-- APP_USER table
CREATE TABLE APP_USER (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LOCATION table
CREATE TABLE LOCATION (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL DEFAULT 'N/A'
);

-- EVENT table
CREATE TABLE EVENT (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES APP_USER(id),
    location_id INTEGER REFERENCES LOCATION(id),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    date_time TIMESTAMP NOT NULL,
    capacity INTEGER,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ATTENDANCE table
CREATE TABLE ATTENDANCE (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES APP_USER(id),
    event_id INTEGER REFERENCES EVENT(id),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

-- NEARBY_PLACE table
CREATE TABLE NEARBY_PLACE (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'N/A'
);

-- LOCATION_NEARBY_PLACE table
CREATE TABLE LOCATION_NEARBY_PLACE (
    id SERIAL PRIMARY KEY,
    location_id INTEGER REFERENCES LOCATION(id),
    nearby_place_id INTEGER REFERENCES NEARBY_PLACE(id),
    distance FLOAT NOT NULL
);